import { NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';

const GEMINI_API_KEY = "AQ.Ab8RN6IH54Zu_Axr3MW02p_TgrhAn8LTAJW-BjA2GJ-IgGGcpg";

// 🟢 استفاده مستقیم از مقادیر ثابت و معتبر برای جلوگیری از خطای خالی بودن متغیر محیطی
const TELEGRAM_BOT_TOKEN = "8994358206:AAHUpoHpMpqdnTxA_J30-xMipDg4l0vhBV8";
const TELEGRAM_CHAT_ID = "5195615040";

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || "";
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || "";
const supabase = createClient(supabaseUrl, supabaseServiceKey, {
    auth: { persistSession: false }
});

export async function POST(req: Request) {
    try {
        const body = await req.json();
        const { ticketId, userId, userEmail, prompt, history, attachmentUrl } = body;

        if (!ticketId || !prompt) {
            return NextResponse.json({ error: 'Missing data' }, { status: 400 });
        }

        // ۱. بررسی وضعیت تیکت (اگر به ادمین وصل شده، هوش مصنوعی کاملاً خاموش است)
        const { data: ticketData } = await supabase.from("tickets").select("status").eq("id", ticketId).single();
        if (ticketData && ticketData.status === "escalated") {
            await supabase.from("ticket_messages").insert({
                ticket_id: ticketId,
                sender_id: userId,
                message_text: prompt,
                attachment_url: attachmentUrl || null
            });
            return NextResponse.json({ escalated: true });
        }

        // ۲. بررسی کلمات کلیدی برای ارجاع به پشتیبانی انسانی
        const escalationKeywords = ["human", "admin", "agent", "انسان", "پشتیبانی", "پشتیبان", "ادمین", "اپراتور", "وصل کن", "مدیر", "refund", "مشاور", "operator", "پشتیبانی وصل", "صحبت کنم"];
        const isAskingForHuman = escalationKeywords.some(k => prompt.toLowerCase().includes(k));

        if (isAskingForHuman) {
            await supabase.from("ticket_messages").insert({
                ticket_id: ticketId,
                sender_id: userId,
                message_text: prompt,
                attachment_url: attachmentUrl || null
            });

            const sysMsg = await triggerEscalation(ticketId, userId, userEmail, prompt);
            return NextResponse.json({ escalated: true, aiMessage: sysMsg });
        }

        // ۳. ثبت پیام کاربر عادی در دیتابیس
        const { error: userMsgError } = await supabase.from("ticket_messages").insert({
            ticket_id: ticketId,
            sender_id: userId,
            message_text: prompt,
            attachment_url: attachmentUrl || null
        });

        if (userMsgError) {
            console.error("🔴 Supabase User Message Insert Error:", userMsgError);
        }

        // ۴. درخواست از هوش مصنوعی با مدل gemini-3.7-flash
        const modelName = "gemini-3.7-flash";
        const url = `https://generativelanguage.googleapis.com/v1beta/models/${modelName}:generateContent?key=${GEMINI_API_KEY}`;

        let formattedContents: any[] = [];
        let lastRole = "";

        if (history && history.length > 0) {
            for (const msg of history) {
                const role = msg.isUser ? "user" : "model";
                if (role === lastRole) {
                    formattedContents[formattedContents.length - 1].parts[0].text += `\n${msg.text}`;
                } else {
                    formattedContents.push({ role, parts: [{ text: msg.text }] });
                    lastRole = role;
                }
            }
        }

        if (lastRole === "user") {
            formattedContents[formattedContents.length - 1].parts[0].text += `\n${prompt}`;
        } else {
            formattedContents.push({ role: "user", parts: [{ text: prompt }] });
        }

        const payload = {
            systemInstruction: {
                parts: [{ text: "You are Safi Academy's official support AI. Be polite, concise, and helpful. If the user speaks Persian, answer in Persian. Do not use markdown formats." }]
            },
            contents: formattedContents
        };

        const response = await fetch(url, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(payload)
        });

        if (!response.ok) {
            const errorText = await response.text();
            console.error("🔴 Gemini API Error Details:", errorText);
            throw new Error(`Gemini Rejected Request: ${errorText}`);
        }

        const data = await response.json();

        if (!data.candidates || data.candidates.length === 0) {
            throw new Error("No response generated by Gemini.");
        }

        const aiText = data.candidates[0].content.parts[0].text;

        // ۵. ثبت پاسخ هوش مصنوعی در دیتابیس
        const { error: aiMsgError } = await supabase.from("ticket_messages").insert({
            ticket_id: ticketId,
            sender_id: null,
            message_text: aiText
        });

        if (aiMsgError) {
            console.error("🔴 Supabase AI Message Insert Error:", aiMsgError);
        }

        return NextResponse.json({ escalated: false, aiMessage: aiText });

    } catch (error: any) {
        console.error("API Route Error:", error.message || error);
        return NextResponse.json({ error: 'Internal Server Error', details: error.message }, { status: 500 });
    }
}

async function triggerEscalation(ticketId: string, userId: string, userEmail: string, lastPrompt: string) {
    // تغییر وضعیت تیکت به escalated در دیتابیس
    await supabase.from("tickets").update({ status: "escalated" }).eq("id", ticketId);

    const isPersian = /[\u0600-\u06FF]/.test(lastPrompt);

    const sysMsg = isPersian
        ? "پیام شما موفقانه به تیم پشتیبانی انسانی ارسال شد، به زودی پی‌گیری خواهد شد."
        : "Your message has been successfully sent to our human support team and will be followed up shortly.";

    await supabase.from("ticket_messages").insert({
        ticket_id: ticketId,
        sender_id: null,
        message_text: sysMsg
    });

    const telegramText = `⚠️ <b>URGENT: Human Support Requested!</b>\n👤 User Email: ${userEmail}\n🆔 User ID: <code>${userId}</code>\n📌 Ticket ID: <code>${ticketId}</code>\n💬 Last Message: "${lastPrompt}"\n🤖 System: Chat has been escalated. AI is now muted.`;

    try {
        // 🟢 ارسال درخواست به تلگرام با مدیریت ارور دقیق
        const tgResponse = await fetch(`https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage`, {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({
                chat_id: TELEGRAM_CHAT_ID,
                text: telegramText,
                parse_mode: "HTML",
            }),
        });

        const tgResult = await tgResponse.json();
        if (!tgResult.ok) {
            console.error("🔴 Telegram API Error:", tgResult);
        }
    } catch (tgError) {
        console.error("🔴 Telegram Fetch Failed:", tgError);
    }

    return sysMsg;
}